### ISSUE TITLE
Change TargetFrameworks to netstandard1.4

### ISSUE THREAD

**Issue by snakefoot** [elmahio/Elmah.Io.Client#2]
Change from `netstandard1.1` to `netstandard1.4`

You are depending on `Microsoft.Rest.ClientRuntime v2.3.2` that only supports netstandard1.4.

**Comment by ThomasArdal** [comment]
Sure? https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/2.3.2

**Comment by snakefoot** [comment]
Cheated again, by the automatic upgrade to latest package when browsing nuget. Sorry just ignore this :)

**Comment by ThomasArdal** [comment]
![giphy 2](https://user-images.githubusercontent.com/563206/33653622-e9006390-da6d-11e7-8b3c-fea8c3bfd86d.gif)
