### ISSUE TITLE
Add NetStandard2.0 target framework

### ISSUE THREAD

**Issue by snakefoot** [elmahio/Elmah.Io.Client#3]
This will reduce dependencies for NetCore-applications. Avoids NetCore1-dependencies for NetCore3-applications

Need to update [Microsoft.Rest.ClientRuntime](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime) to ver. 2.3.20 (or newer) for netstandard2.0 + netstandard1.4.

P.S. Any reason why Net45 is not depending on System.Net.Http ? And why are Net46 + NetStandard1 depending on such an old version of System.Net.Http ? Remember NetStandard2.0 does not need dependency on System.Net.Http.

P.P.S. Consider changing Net46 into Net461 so it depends on same nuget-versions as NetStandard2.0 (Leaving net45 + nestandard1.1 as the special ones)

**Comment by ThomasArdal** [comment]
Updating `Microsoft.Rest.ClientRuntime` to at least 2.3.19 is a good idea since there is .NET Standard 2.0 targeting from that version.

I'm curious, in which NetCore1-dependencies can be dropped when targeting .NET Standard 2.0 from `Elmah.Io.Client`? The current .NET Standard 1.4 only depends on `Microsoft.Rest.ClientRuntime`.

> Any reason why Net45 is not depending on System.Net.Http

Good question. I'm pretty sure the explicit dependency on `System.Net.Http` from net46 was because of a problem with the version of `System.Net.Http` package that came with net46 as default. As for referencing older versions, these are the minimum versions. People are very welcome to update to newer versions. We typically don't want to depend on the newest version of everything, since some people may have other packages installed that won't work with the new versions. Makes sense?

> Consider changing Net46 into Net461

You may be right here. But, again, pretty sure there's a problem with .NET 4.6 and `System.Net.Http`. Maybe if we extend Net45 with an explicit version of `System.Net.Http` this would work.

**Comment by snakefoot** [comment]
> Updating Microsoft.Rest.ClientRuntime to at least 2.3.19 is a good idea since there is .NET Standard 2.0 targeting from that version.

Looks like ClientRuntime  ver. 2.3.20 includes an important bug-fix.

> I'm curious, in which NetCore1-dependencies can be dropped when targeting .NET Standard 2.0 from Elmah.Io.Client?

You can remove `System.Net.Http`-dependency. And `NETStandard.Library v1.6.1`

> We typically don't want to depend on the newest version of everything

System.Net.Http ver. 4.3.4 is over one year old

> > Consider changing Net46 into Net461
>
> You may be right here. But, again, pretty sure there's a problem with .NET 4.6 and System.Net.Http

My suggestion is because Microsoft.Rest.ClientRuntime ver 2.3.20 does not support net46 and only net461. Nothing related to System.Net.Http

**Comment by ThomasArdal** [comment]
What do you think about this:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.1' ">
  <PackageReference Include="Microsoft.CSharp" Version="4.0.1" />
  <PackageReference Include="System.Net.Http" Version="4.3.0" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.6" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.4' ">
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.18" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.20" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
  <Reference Include="System" />
  <Reference Include="Microsoft.CSharp" />
  <PackageReference Include="System.Net.Http" Version="4.3.1" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.20" />
</ItemGroup>
  
<ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
  <Reference Include="System" />
  <Reference Include="Microsoft.CSharp" />
  <PackageReference Include="System.Net.Http" Version="4.3.1" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.18" />
</ItemGroup>
  
<ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
  <Reference Include="System" />
  <Reference Include="Microsoft.CSharp" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.6" />
</ItemGroup>
```

**Comment by snakefoot** [comment]
Yes that will work. And will have no breaking changes.


Then one day when the sun shines, then you can remove net46 and just have net461

**Comment by snakefoot** [comment]
I suggest that you update `netstandard1.4` to match  `netstandard2.0`:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.4' ">
   <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.20" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.20" />
</ItemGroup>
```

**Comment by ThomasArdal** [comment]
That would make the `netstandard2.0` target redundant, right? Or am I missing something here?

**Comment by ThomasArdal** [comment]
Ah, I guess you're right. Targeting `netstandard2.0` wouldn't need `NETStandard.Library` then. That's the point, right?

**Comment by snakefoot** [comment]
> Ah, I guess you're right. Targeting netstandard2.0 wouldn't need NETStandard.Library then. That's the point, right?

Exactly. If you are a pure business-logic/math-logic library, that specifies `<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>`. Then it is no sin to just support NetStandard1.1. But when you depend on the whole `NETStandard.Library` then you should also include `netstandard2.0` as TargetFramework, as it will make nuget/builds/deployments faster.

**Comment by ThomasArdal** [comment]
Getting a bit complex. But maybe this:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.1' ">
  <PackageReference Include="Microsoft.CSharp" Version="4.0.1" />
  <PackageReference Include="System.Net.Http" Version="4.3.0" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.6" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.4' ">
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.21" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.21" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
  <Reference Include="System" />
  <Reference Include="Microsoft.CSharp" />
  <PackageReference Include="System.Net.Http" Version="4.3.4" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.18" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
  <Reference Include="System" />
  <Reference Include="Microsoft.CSharp" />
  <PackageReference Include="System.Net.Http" Version="4.3.4" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.21" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
  <Reference Include="System" />
  <Reference Include="Microsoft.CSharp" />
  <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.6" />
</ItemGroup>
```

**Comment by snakefoot** [comment]
I think it looks good. Then in a future version one can remove "net46" and "netstandard1.1"

**Comment by ThomasArdal** [comment]
Yep. There's a long way for that to happen, though :smile: Thank you for your input. Will release a new prerelease of `Elmah.Io.Client` soon and start testing the integrations on top of that 👍

**Comment by snakefoot** [comment]
Excellent. Created https://github.com/elmahio/elmah.io.nlog/pull/10
